# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

VCMM <- function(response, subject, response_time, vcm_covariates, fixed_covariates, estimated_time, random_effect, estimate_variance_components, tuning_strategy, kernel_scale, kernel_scale_factor, n_kernel_scale, alpha, lambda, lambda_factor, n_lambda, adaptive, penalize_intercept, max_iter, rel_tol, nfolds, cv_seed, progress_bar) {
    .Call('_VCMM_VCMM', PACKAGE = 'VCMM', response, subject, response_time, vcm_covariates, fixed_covariates, estimated_time, random_effect, estimate_variance_components, tuning_strategy, kernel_scale, kernel_scale_factor, n_kernel_scale, alpha, lambda, lambda_factor, n_lambda, adaptive, penalize_intercept, max_iter, rel_tol, nfolds, cv_seed, progress_bar)
}

VCMMBoot <- function(response, subject, response_time, vcm_covariates, fixed_covariates, estimated_time, random_effect, estimate_variance_components, kernel_scale, alpha, lambda, adaptive, penalize_intercept, max_iter, rel_tol, n_samples, progress_bar) {
    .Call('_VCMM_VCMMBoot', PACKAGE = 'VCMM', response, subject, response_time, vcm_covariates, fixed_covariates, estimated_time, random_effect, estimate_variance_components, kernel_scale, alpha, lambda, adaptive, penalize_intercept, max_iter, rel_tol, n_samples, progress_bar)
}

