# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

VCMM <- function(response, subject, response_time, random_design, vcm_covariates, fixed_covariates, estimated_time, kernel_scale, n_kernel_scale, alpha, lambda, lambda_factor, n_lambda, max_iter, mult) {
    .Call(`_VCM_VCMM`, response, subject, response_time, random_design, vcm_covariates, fixed_covariates, estimated_time, kernel_scale, n_kernel_scale, alpha, lambda, lambda_factor, n_lambda, max_iter, mult)
}

to_list_by_subject <- function(subject, array) {
    .Call(`_VCM_to_list_by_subject`, subject, array)
}

