# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

VCMM <- function(response, subject, response_time, random_design, vcm_covariates, fixed_covariates, estimated_time, tuning_strategy, kernel_scale, kernel_scale_factor, n_kernel_scale, alpha, lambda, lambda_factor, n_lambda, max_iter, mult, ebic_factor, rel_tol, orthogonal_search_max_rounds, bissection_max_evals, nfolds, cv_seed) {
    .Call('_VCMM_VCMM', PACKAGE = 'VCMM', response, subject, response_time, random_design, vcm_covariates, fixed_covariates, estimated_time, tuning_strategy, kernel_scale, kernel_scale_factor, n_kernel_scale, alpha, lambda, lambda_factor, n_lambda, max_iter, mult, ebic_factor, rel_tol, orthogonal_search_max_rounds, bissection_max_evals, nfolds, cv_seed)
}

